In [1]:
import sys

print(sys.version)
print(sys.executable)

3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
d:\anaconda_python\python.exe

<h3 style="color:white">Import Dataset</h3>

In [11]:
import pandas as pd

df = pd.read_csv("../data/raw/ChargingRecords.csv")

df.head(5)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,2022-09-15,20:54:02,2022-09-15,23:59:13,2022-09-15 20:54,2022-09-15 23:59,185,20.36
1,0,1,1,hotel,0,2022-09-14,20:01:05,2022-09-14,21:31:04,2022-09-14 20:01,2022-09-14 21:31,90,10.19
2,0,1,1,hotel,0,2022-09-14,18:54:30,2022-09-14,19:54:29,2022-09-14 18:54,2022-09-14 19:54,60,6.78
3,0,1,1,hotel,0,2022-09-29,18:32:51,2022-09-30,0:16:42,2022-09-29 18:32,2022-09-30 0:16,344,37.65
4,0,1,1,hotel,0,2022-09-25,19:30:15,2022-09-26,0:30:14,2022-09-25 19:30,2022-09-26 0:30,300,33.81

In [12]:
df.tail(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
72853,2388,2670,0,sightseeing,1,2021-10-03,13:52:14,2021-10-03,14:32:13,2021-10-03 13:52,2021-10-03 14:32,40,12.20
72854,2388,2671,0,company,1,2021-11-18,11:37:44,2021-11-18,11:45:37,2021-11-18 11:37,2021-11-18 11:45,8,3.80
72855,2388,2671,0,company,1,2021-10-30,17:29:02,2021-10-30,17:36:47,2021-10-30 17:29,2021-10-30 17:36,8,3.67

<h3 style="color:white">Dataset Information</h3>

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  object
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  object
 6   StartTime       72856 non-null  object
 7   EndDay          72856 non-null  object
 8   EndTime         72856 non-null  object
 9   StartDatetime   72856 non-null  object
 10  EndDatetime     72856 non-null  object
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: float64(1), int64(5), object(7)
memory usage: 7.2+ MB

In [14]:
df.shape

(72856, 13)

In [15]:
df.columns

Index(['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType',
       'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime',
       'EndDatetime', 'Duration', 'Demand'],
      dtype='object')

<h3 style="color:white">Dataset Preview</h3>

In [22]:
df.isnull().sum()

UserID            0
ChargerID         0
ChargerCompany    0
Location          0
ChargerType       0
StartDay          0
StartTime         0
EndDay            0
EndTime           0
StartDatetime     0
EndDatetime       0
Duration          0
Demand            0
dtype: int64

<h3 style="color:white">Duplicate Check</h3>

In [31]:
df.duplicated().sum()

np.int64(13)

In [30]:
df[df.duplicated(keep=False)].head(5)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
28856,329,214,1,public area,0,2022-02-12,7:22:40,2022-02-12,15:44:27,2022-02-12 7:22,2022-02-12 15:44,502,54.34
28857,329,214,1,public area,0,2022-02-12,7:22:40,2022-02-12,15:44:27,2022-02-12 7:22,2022-02-12 15:44,502,54.34
28858,329,214,1,public area,0,2022-02-15,19:29:42,2022-02-15,23:03:11,2022-02-15 19:29,2022-02-15 23:03,213,23.68
28859,329,214,1,public area,0,2022-02-15,19:29:42,2022-02-15,23:03:11,2022-02-15 19:29,2022-02-15 23:03,213,23.68
28861,329,214,1,public area,0,2022-02-17,18:53:55,2022-02-18,3:38:13,2022-02-17 18:53,2022-02-18 3:38,524,58.06

In [28]:
df[df.duplicated(keep=False)].shape

(26, 13)

In [32]:
df = df.drop_duplicates()

print("New shape:", df.shape)

New shape: (72843, 13)

In [33]:
df[df.duplicated(keep=False)].shape

(0, 13)

<h3 style="color:white">Data Types</h3>

In [34]:
df.dtypes

UserID              int64
ChargerID           int64
ChargerCompany      int64
Location           object
ChargerType         int64
StartDay           object
StartTime          object
EndDay             object
EndTime            object
StartDatetime      object
EndDatetime        object
Duration            int64
Demand            float64
dtype: object

<h3 style="color:white">Convert Datetime Columns</h3>

In [35]:
df["StartDatetime"] = pd.to_datetime(df["StartDatetime"])
df["EndDatetime"] = pd.to_datetime(df["EndDatetime"])

df[["StartDatetime", "EndDatetime"]].dtypes

StartDatetime    datetime64[ns]
EndDatetime      datetime64[ns]
dtype: object

<h3 style="color:white">Check Data Types After Cleaning</h3>

In [36]:
df.dtypes

UserID                     int64
ChargerID                  int64
ChargerCompany             int64
Location                  object
ChargerType                int64
StartDay                  object
StartTime                 object
EndDay                    object
EndTime                   object
StartDatetime     datetime64[ns]
EndDatetime       datetime64[ns]
Duration                   int64
Demand                   float64
dtype: object

<h3 style="color:white">Numerical Data Summary</h3>

In [37]:
df.describe()

,UserID,ChargerID,ChargerCompany,ChargerType,StartDatetime,EndDatetime,Duration,Demand
count,72843.000000,72843.000000,72843.000000,72843.000000,72843,72843,72843.000000,72843.000000
mean,338.084716,525.404143,0.627500,0.205195,2022-04-19 11:51:21.575717888,2022-04-19 14:26:51.334788608,151.183998,17.442667
min,0.000000,1.000000,0.000000,0.000000,2021-09-30 17:14:00,2021-10-01 00:07:00,-29.000000,0.010000
25%,0.000000,107.000000,0.000000,0.000000,2022-01-25 21:39:30,2022-01-26 02:36:00,40.000000,7.530000
50%,62.000000,301.000000,1.000000,0.000000,2022-04-27 14:19:00,2022-04-27 15:39:00,112.000000,14.100000
75%,407.000000,738.000000,1.000000,0.000000,2022-07-17 09:58:30,2022-07-17 11:47:00,202.000000,23.200000
max,2501.000000,2671.000000,1.000000,1.000000,2022-09-30 23:11:00,2022-09-30 23:52:00,1573.000000,97.000000
std,553.916404,569.481406,0.483474,0.403847,NaN,NaN,146.420312,13.491446

<h3 style="color:white">Check Negative Duration</h3>

In [38]:
df[df["Duration"] < 0][["StartDatetime", "EndDatetime", "Duration"]]

            StartDatetime         EndDatetime  Duration
55422 2022-02-15 15:04:00 2022-02-15 14:35:00       -29
55425 2022-02-24 14:27:00 2022-02-24 14:18:00        -9
55427 2022-01-17 14:47:00 2022-01-17 14:39:00        -8
55455 2022-04-29 18:58:00 2022-04-29 18:52:00        -6
55457 2022-05-07 16:24:00 2022-05-07 16:03:00       -21
55458 2022-04-29 15:48:00 2022-04-29 15:43:00        -6
55459 2022-03-27 15:17:00 2022-03-27 15:10:00        -7
55460 2022-02-05 18:52:00 2022-02-05 18:50:00        -2
55464 2022-05-08 12:02:00 2022-05-08 11:42:00       -20
55465 2022-01-09 14:29:00 2022-01-09 14:20:00        -9
55469 2022-04-07 12:25:00 2022-04-07 12:12:00       -13
57800 2022-04-09 11:29:00 2022-04-09 11:23:00        -6
57802 2022-05-05 17:48:00 2022-05-05 17:31:00       -16
57803 2022-04-17 18:59:00 2022-04-17 18:54:00        -5
63503 2022-03-19 15:32:00 2022-03-19 15:24:00        -8
63504 2022-03-22 17:19:00 2022-03-22 16:55:00       -24
65029 2022-03-30 13:20:00 2022-03-30 13:04:00       -16

<h3 style="color:white">Recalculate Duration</h3>

In [39]:
df["Duration"] = (
    df["EndDatetime"] - df["StartDatetime"]
).dt.total_seconds() / 60

df["Duration"] = df["Duration"].astype(int)

df["Duration"].describe()

count    72843.000000
mean       155.495985
std        159.176710
min        -29.000000
25%         41.000000
50%        114.000000
75%        204.000000
max       4717.000000
Name: Duration, dtype: float64

<h3 style="color:white">Remove Invalid Duration Records</h3>

In [40]:
df = df[df["Duration"] >= 0].copy()

df.shape

(72826, 13)

<h3 style="color:white">Verify Duration</h3>

In [41]:
df[df["Duration"] < 0].shape

(0, 13)

<h3 style="color:white">Check Categorical Values</h3>

In [42]:
print("Location:", df["Location"].nunique())
print("ChargerType:", df["ChargerType"].nunique())
print("ChargerCompany:", df["ChargerCompany"].nunique())

Location: 14
ChargerType: 2
ChargerCompany: 2

<h3 style="color:white">View Categorical Values</h3>

In [43]:
print("Locations:")
print(df["Location"].unique())

print("\nCharger Types:")
print(df["ChargerType"].unique())

print("\nCharger Companies:")
print(df["ChargerCompany"].unique())

Locations:
['hotel' 'company' 'apartment' 'resort' 'public area' 'public institution'
 'restaurant' 'accommodation' 'golf' 'sightseeing' 'market' 'camping'
 'public parking lot' 'bus garage']

Charger Types:
[0 1]

Charger Companies:
[1 0]

<h3 style="color:white">Check Day and Time Values</h3>

In [44]:
print("StartDay:")
print(df["StartDay"].unique())

print("\nEndDay:")
print(df["EndDay"].unique())

print("\nStartTime sample:")
print(df["StartTime"].head())

print("\nEndTime sample:")
print(df["EndTime"].head())

StartDay:
['2022-09-15' '2022-09-14' '2022-09-29' '2022-09-25' '2022-09-24'
 '2022-08-11' '2022-08-10' '2022-08-09' '2022-08-07' '2022-08-06'
 '2022-08-05' '2022-08-23' '2022-08-22' '2022-08-19' '2022-08-18'
 '2022-08-17' '2022-07-02' '2022-07-03' '2022-07-05' '2022-07-08'
 '2022-07-14' '2022-07-27' '2022-06-07' '2022-06-09' '2022-06-10'
 '2022-06-18' '2022-06-23' '2022-05-08' '2022-05-09' '2022-05-12'
 '2022-05-14' '2022-05-15' '2022-05-16' '2022-05-23' '2022-05-27'
 '2022-04-08' '2022-04-14' '2022-04-16' '2022-04-27' '2022-03-01'
 '2022-03-02' '2022-03-03' '2022-03-10' '2022-03-12' '2022-03-13'
 '2022-03-18' '2022-03-30' '2022-03-31' '2022-02-01' '2022-02-04'
 '2022-02-11' '2022-02-14' '2022-02-20' '2022-02-27' '2022-01-27'
 '2021-12-07' '2021-12-17' '2021-12-20' '2021-12-24' '2022-09-08'
 '2022-09-22' '2022-08-14' '2022-08-04' '2022-08-03' '2022-08-02'
 '2022-08-24' '2022-08-21' '2022-08-20' '2022-08-16' '2022-07-29'
 '2022-07-25' '2022-07-22' '2022-07-21' '2022-07-18' '2022-07-07'
 '2022-07-04' '2022-07-01' '2022-06-03' '2022-06-08' '2022-06-12'
 '2022-06-14' '2022-06-21' '2022-05-01' '2022-05-03' '2022-05-20'
 '2022-05-25' '2022-05-29' '2022-05-30' '2022-04-01' '2022-04-06'
 '2022-04-25' '2022-04-29' '2022-03-27' '2022-03-29' '2022-09-18'
 '2022-06-17' '2022-02-09' '2022-07-28' '2022-09-13' '2022-08-01'
 '2022-09-07' '2022-09-11' '2021-12-19' '2022-09-12' '2022-02-12'
 '2022-07-12' '2022-09-10' '2022-07-30' '2021-12-16' '2022-03-20'
 '2022-06-28' '2022-06-29' '2022-06-30' '2022-05-13' '2022-05-28'
 '2022-07-31' '2022-05-10' '2022-02-07' '2022-02-23' '2022-09-28'
 '2022-06-19' '2022-07-10' '2022-06-06' '2022-03-21' '2022-09-23'
 '2022-04-23' '2022-09-21' '2022-02-25' '2022-09-17' '2022-09-16'
 '2022-08-15' '2022-04-15' '2022-07-16' '2022-04-19' '2022-04-20'
 '2022-08-13' '2022-08-12' '2022-08-08' '2022-05-07' '2022-05-06'
 '2022-05-05' '2022-02-03' '2022-01-29' '2022-02-16' '2022-02-17'
 '2022-07-17' '2022-03-05' '2022-08-25' '2022-04-05' '2022-07-26'
 '2021-12-26' '2021-12-27' '2022-02-18' '2022-02-19' '2022-07-20'
 '2022-05-19' '2022-04-12' '2022-06-26' '2021-12-18' '2022-07-24'
 '2022-06-24' '2021-12-15' '2022-07-23' '2022-02-08' '2022-02-15'
 '2022-02-24' '2022-07-11' '2022-04-18' '2022-04-24' '2022-07-15'
 '2022-06-22' '2022-07-13' '2022-07-09' '2022-04-26' '2022-05-18'
 '2022-06-11' '2022-05-31' '2022-04-04' '2022-06-25' '2022-06-01'
 '2022-06-04' '2022-05-04' '2022-05-24' '2022-03-14' '2022-03-07'
 '2022-04-10' '2022-03-08' '2022-05-11' '2022-05-22' '2022-03-23'
 '2022-04-17' '2022-04-21' '2022-03-19' '2022-04-13' '2022-04-07'
 '2022-03-16' '2022-02-05' '2022-03-24' '2022-02-10' '2022-03-26'
 '2022-03-09' '2022-03-22' '2022-02-02' '2021-12-21' '2022-02-22'
 '2022-02-06' '2022-02-26' '2022-02-28' '2022-01-30' '2022-01-28'
 '2021-11-17' '2021-12-25' '2021-11-25' '2021-11-29' '2021-11-24'
 '2021-11-04' '2022-09-06' '2022-09-01' '2022-09-19' '2022-08-28'
 '2022-08-27' '2022-09-02' '2022-08-26' '2022-09-27' '2022-08-31'
 '2022-08-29' '2022-09-26' '2022-09-20' '2022-07-06' '2022-07-19'
 '2022-06-02' '2022-05-02' '2022-05-17' '2022-05-21' '2022-05-26'
 '2022-04-11' '2022-04-30' '2022-03-04' '2022-03-06' '2022-02-13'
 '2021-12-31' '2022-01-01' '2022-01-02' '2022-01-03' '2022-01-04'
 '2022-01-06' '2022-01-11' '2022-01-12' '2022-01-13' '2022-01-14'
 '2022-01-15' '2022-01-16' '2022-01-17' '2022-01-18' '2022-01-19'
 '2022-01-20' '2022-01-21' '2022-01-23' '2022-01-24' '2022-01-31'
 '2021-11-30' '2021-12-01' '2021-12-05' '2021-12-06' '2021-12-08'
 '2021-12-10' '2021-12-14' '2021-12-22' '2021-12-23' '2021-12-28'
 '2021-12-29' '2021-11-02' '2021-11-03' '2021-11-10' '2021-11-11'
 '2021-11-18' '2021-11-20' '2021-11-23' '2021-11-28' '2021-10-01'
 '2021-10-04' '2021-10-06' '2021-10-08' '2021-10-10' '2021-10-13'
 '2021-10-17' '2021-10-20' '2021-10-26' '2021-10-29' '2022-03-11'
 '2022-09-30' '2022-09-09' '2021-12-30' '2021-11-22' '2021-10-14'
 '2021-12-09' '2021-12-11' '2021-10-24' '2022-01-08' '2022-01-09'
 '2022-01-05' '2022-04-22' '2022-03-25' '2022-01-10' '2022-01-25'
 '2021-12-02' '2021-11-01' '2021-11-06' '2021-11-09' '2021-11-21'
 '2022-06-16' '2021-11-26' '2022-06-27' '2022-04-03' '2021-10-28'
 '2021-11-12' '2021-11-05' '2021-10-11' '2022-06-13' '2022-06-15'
 '2022-04-02' '2021-11-15' '2021-11-16' '2022-03-15' '2021-12-13'
 '2021-11-27' '2021-11-14' '2021-10-18' '2021-10-19' '2021-10-12'
 '2021-11-13' '2022-03-28' '2021-10-21' '2021-10-22' '2021-10-15'
 '2021-10-16' '2022-01-22' '2021-10-25' '2021-10-27' '2021-10-07'
 '2021-10-09' '2021-10-02' '2022-01-26' '2022-08-30' '2021-11-08'
 '2022-06-05' '2022-03-17' '2021-12-03' '2021-10-23' '2022-09-03'
 '2022-06-20' '2022-01-07' '2021-12-12' '2021-11-19' '2021-10-05'
 '2021-10-30' '2022-04-09' '2022-04-28' '2021-11-07' '2021-10-03'
 '2021-10-31' '2022-09-04' '2022-02-21' '2021-12-04' '2022-09-05'
 '2021-09-30']

EndDay:
['2022-09-15' '2022-09-14' '2022-09-30' '2022-09-26' '2022-09-24'
 '2022-08-11' '2022-08-09' '2022-08-07' '2022-08-05' '2022-08-24'
 '2022-08-23' '2022-08-22' '2022-08-19' '2022-08-18' '2022-08-17'
 '2022-07-02' '2022-07-03' '2022-07-05' '2022-07-09' '2022-07-14'
 '2022-07-27' '2022-07-28' '2022-06-07' '2022-06-09' '2022-06-10'
 '2022-06-18' '2022-06-23' '2022-05-08' '2022-05-09' '2022-05-12'
 '2022-05-14' '2022-05-15' '2022-05-17' '2022-05-23' '2022-05-27'
 '2022-04-09' '2022-04-14' '2022-04-17' '2022-04-28' '2022-03-01'
 '2022-03-02' '2022-03-03' '2022-03-11' '2022-03-12' '2022-03-13'
 '2022-03-18' '2022-03-30' '2022-03-31' '2022-02-01' '2022-02-04'
 '2022-02-11' '2022-02-14' '2022-02-20' '2022-02-27' '2022-01-27'
 '2021-12-07' '2021-12-17' '2021-12-20' '2021-12-21' '2021-12-24'
 '2022-09-08' '2022-09-29' '2022-09-23' '2022-08-14' '2022-08-04'
 '2022-08-03' '2022-08-25' '2022-08-21' '2022-08-20' '2022-08-16'
 '2022-07-30' '2022-07-25' '2022-07-22' '2022-07-21' '2022-07-18'
 '2022-07-08' '2022-07-07' '2022-06-03' '2022-06-08' '2022-06-12'
 '2022-06-15' '2022-06-21' '2022-05-01' '2022-05-04' '2022-05-20'
 '2022-05-25' '2022-05-29' '2022-05-30' '2022-04-01' '2022-04-06'
 '2022-04-08' '2022-04-25' '2022-04-29' '2022-03-27' '2022-03-29'
 '2022-02-28' '2022-09-18' '2022-06-17' '2022-02-09' '2022-09-13'
 '2022-08-01' '2022-09-07' '2022-09-11' '2021-12-19' '2022-09-12'
 '2022-02-13' '2022-07-12' '2022-09-10' '2021-12-16' '2022-03-20'
 '2022-06-28' '2022-06-30' '2022-05-13' '2022-05-28' '2022-07-31'
 '2022-05-10' '2022-02-07' '2022-02-12' '2022-02-23' '2022-09-28'
 '2022-06-20' '2022-07-10' '2022-03-21' '2022-09-25' '2022-04-24'
 '2022-07-04' '2022-09-21' '2022-02-25' '2022-09-16' '2022-08-15'
 '2022-04-15' '2022-07-16' '2022-03-19' '2022-04-19' '2022-04-20'
 '2022-08-13' '2022-08-10' '2022-07-29' '2022-08-08' '2021-12-25'
 '2022-05-07' '2022-05-06' '2022-08-02' '2022-04-23' '2022-02-03'
 '2022-01-29' '2022-06-19' '2022-02-16' '2022-02-17' '2022-07-17'
 '2022-03-05' '2022-04-05' '2021-12-26' '2021-12-27' '2022-02-19'
 '2022-07-20' '2022-05-03' '2022-05-19' '2022-04-12' '2022-06-26'
 '2021-12-18' '2022-07-26' '2022-07-24' '2022-06-24' '2021-12-15'
 '2022-07-23' '2022-02-08' '2022-02-24' '2022-07-11' '2022-04-18'
 '2022-07-15' '2022-07-01' '2022-06-22' '2022-06-06' '2022-06-29'
 '2022-04-26' '2022-04-13' '2022-05-18' '2022-06-11' '2022-05-31'
 '2022-04-04' '2022-06-25' '2022-06-01' '2022-06-04' '2022-05-24'
 '2022-03-14' '2022-03-07' '2022-04-10' '2022-03-09' '2022-05-11'
 '2022-05-22' '2022-05-05' '2022-04-16' '2022-03-23' '2022-04-21'
 '2022-04-22' '2022-04-02' '2022-03-17' '2022-02-05' '2022-03-04'
 '2022-03-24' '2022-02-10' '2022-03-26' '2022-03-10' '2022-03-08'
 '2022-03-22' '2022-02-02' '2022-02-22' '2022-02-15' '2022-02-06'
 '2022-02-26' '2022-01-30' '2022-01-28' '2021-11-17' '2021-11-25'
 '2021-11-29' '2021-11-24' '2021-11-04' '2022-09-06' '2022-09-01'
 '2022-09-19' '2022-09-17' '2022-08-28' '2022-08-26' '2022-09-03'
 '2022-08-31' '2022-08-29' '2022-08-27' '2022-09-22' '2022-09-20'
 '2022-08-12' '2022-07-06' '2022-07-13' '2022-07-19' '2022-06-02'
 '2022-05-16' '2022-05-21' '2022-05-26' '2022-04-07' '2022-04-30'
 '2022-03-06' '2022-01-01' '2022-01-02' '2022-01-03' '2022-01-04'
 '2022-01-07' '2022-01-11' '2022-01-13' '2022-01-14' '2022-01-15'
 '2022-01-16' '2022-01-17' '2022-01-18' '2022-01-19' '2022-01-20'
 '2022-01-21' '2022-01-23' '2022-01-24' '2022-01-31' '2021-12-01'
 '2021-12-05' '2021-12-06' '2021-12-08' '2021-12-10' '2021-12-14'
 '2021-12-22' '2021-12-23' '2021-12-28' '2021-12-29' '2021-11-02'
 '2021-11-03' '2021-11-10' '2021-11-11' '2021-11-18' '2021-11-20'
 '2021-11-21' '2021-11-23' '2021-11-28' '2021-11-30' '2021-10-01'
 '2021-10-04' '2021-10-06' '2021-10-08' '2021-10-10' '2021-10-13'
 '2021-10-17' '2021-10-20' '2021-10-26' '2021-10-29' '2022-09-02'
 '2022-08-30' '2022-09-09' '2021-12-30' '2021-11-22' '2021-10-14'
 '2021-10-15' '2022-04-11' '2021-12-31' '2021-12-09' '2022-09-27'
 '2021-11-12' '2021-12-11' '2021-10-24' '2022-01-08' '2022-01-09'
 '2022-01-06' '2022-08-06' '2022-03-25' '2022-01-10' '2022-01-25'
 '2021-12-02' '2021-11-01' '2021-11-06' '2021-11-09' '2021-11-27'
 '2022-06-27' '2021-10-28' '2022-02-18' '2021-10-11' '2022-06-13'
 '2022-01-05' '2022-05-02' '2021-11-15' '2021-11-16' '2022-03-15'
 '2021-10-02' '2021-12-13' '2021-11-14' '2021-10-18' '2022-04-27'
 '2021-10-19' '2022-04-03' '2021-11-13' '2022-03-28' '2021-10-21'
 '2021-10-23' '2022-01-22' '2021-11-26' '2021-10-25' '2021-10-27'
 '2021-10-07' '2021-10-09' '2022-01-26' '2021-11-08' '2021-10-12'
 '2022-06-05' '2022-03-16' '2022-06-14' '2021-12-04' '2022-01-12'
 '2022-09-04' '2021-12-12' '2021-11-05' '2021-11-19' '2021-10-05'
 '2021-10-30' '2022-06-16' '2021-12-03' '2021-11-07' '2021-10-03'
 '2021-10-22' '2021-10-31' '2021-10-16' '2022-02-21' '2022-09-05']

StartTime sample:
0    20:54:02
1    20:01:05
2    18:54:30
3    18:32:51
4    19:30:15
Name: StartTime, dtype: object

EndTime sample:
0    23:59:13
1    21:31:04
2    19:54:29
3     0:16:42
4     0:30:14
Name: EndTime, dtype: object

<h3 style="color:white">Check Demand Values</h3>

In [45]:
print("Minimum Demand:", df["Demand"].min())
print("Maximum Demand:", df["Demand"].max())
print("Zero Demand:", (df["Demand"] == 0).sum())
print("Negative Demand:", (df["Demand"] < 0).sum())

Minimum Demand: 0.01
Maximum Demand: 97.0
Zero Demand: 0
Negative Demand: 0

<h3 style="color:white">Final Missing Value Check</h3>

In [46]:
df.isnull().sum()

UserID            0
ChargerID         0
ChargerCompany    0
Location          0
ChargerType       0
StartDay          0
StartTime         0
EndDay            0
EndTime           0
StartDatetime     0
EndDatetime       0
Duration          0
Demand            0
dtype: int64

<h3 style="color:white">Save Cleaned Dataset</h3>

In [47]:
df.to_csv("../data/processed/ChargingRecords_cleaned.csv", index=False)